spring.application.name=app

server.port=80

#application-xxx.properties
spring.profiles.active=private,cloud,dev

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521/xe
spring.datasource.username=C##SEMI
spring.datasource.password=1234

# config

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL

# view resolver

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#tomcat part count
server.tomcat.max-part-count=100

#page
page.pageLimit=5
page.boardLimit=10

